builds:
  - main: ./cmd/lassie
    binary: lassie
    ldflags:
      # Sets the version variable in the build package to the build version prefixed with a 'v'
      # Sets the main.date to a static date for checksum verification. See https://goreleaser.com/customization/builds/#reproducible-builds.
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -X main.builtBy=goreleaser -X github.com/filecoin-project/lassie/pkg/build.version=v{{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 'amd64'
      - 'arm64'
    # Change to a static date for checksum verification. See https://goreleaser.com/customization/builds/#reproducible-builds.
    mod_timestamp: '{{.CommitTimestamp}}'
universal_binaries:
  - replace: true
archives:
  - format_overrides:
    - goos: windows
      format: zip
    - goos: darwin
      format: zip
release:
  mode: keep-existing
changelog:
  skip: true